@startuml

[*] --> start_parsing
start_parsing --> parsing_field : if more fields to parse
start_parsing : def convert(string)
parsing_field --> start_parsing
start_parsing --> [*] : if no more fields to parse

@enduml